docs (v6.1.0)
AkaruiDevelopment/aoi.js-documentation pull request #13
Opened 2023-02-02 06:48 UTC by Faf4a

1. changed every
    - yes -> true
    - no -> false
2. renamed server -> guild
3. fixed last missing things

2023-02-02 19:31 UTC, Leref requested changes

2023-02-02 19:31 UTC, Leref commented on src/introduction/introduction.md
> +**node.js 17.0.0 or newer is required.**
16.9.0 required.

2023-02-02 19:31 UTC, Leref commented on src/guides/1setup.md
> +**node.js 17.0.0 or newer is required.**
16.9.0 required.

2023-02-03 05:46 UTC, Faf4a commented on src/guides/1setup.md
> +**node.js 17.0.0 or newer is required.**
fixed

2023-02-03 05:46 UTC, Faf4a commented on src/introduction/introduction.md
> +**node.js 17.0.0 or newer is required.**
fixed

2023-02-14 03:39 UTC, Leref approved these changes

2023-02-14 03:39 UTC, merged