Update(music docs)
AkaruiDevelopment/aoi.js-documentation pull request #15
Opened 2023-02-21 18:34 UTC by USERSATOSHI

2023-02-22 04:45 UTC, Leref requested changes
Needed changes.

2023-02-22 04:45 UTC, Leref commented on .gitignore
> +/converter.js
Remove this.

2023-02-22 04:45 UTC, Leref commented on src/guides/@akarui/aoi.music.md
> +voice.addPlugin(PluginName.Cacher, new Cacher("memory" /* or "disk" */));
Space / break here

2023-02-22 15:41 UTC, USERSATOSHI commented on src/guides/@akarui/aoi.music.md
> +voice.addPlugin(PluginName.Cacher, new Cacher("memory" /* or "disk" */));
done

2023-02-22 19:05 UTC, Leref commented
Fix the conflicting.

2023-02-26 06:05 UTC, USERSATOSHI commented
> Fix the conflicting.

i can't see what lines are conflicting with each other as i dont have write access

2023-02-27 16:40 UTC, Leref requested changes
Needed before approving.

2023-02-27 16:40 UTC, Leref commented on src/guides/akarui/aoi.music.md
> +title: akarui/aoi.music
Keep only topic name.
just `aoi.music`.

2023-02-27 16:40 UTC, Leref commented on src/guides/akarui/aoi.music.md
> +id: akarui/aoi.music
keep the name only of the topic

2023-02-27 16:40 UTC, Leref commented on src/guides/akarui/aoi.music.md
> +
Don't escape

2023-02-27 16:43 UTC, Leref requested changes
Last thing to be accepted.

2023-02-27 16:43 UTC, Leref commented on src/guides/akarui/aoi.music.md
> +
Remove

2023-02-27 16:43 UTC, Leref commented on src/guides/akarui/aoi.music.md
> +
Remove

2023-02-27 16:43 UTC, Leref commented on src/guides/akarui/aoi.music.md
> +
Remove

2023-02-27 16:47 UTC, merged