Updated some files.
AkaruiDevelopment/aoi.js-documentation pull request #17
Opened 2023-02-22 13:44 UTC by Faf4a

- Fixed examples.
- Added examples.
- Fixed some Ids.
- Made it so AoiEngine wont break ._.

2023-02-22 19:00 UTC, Leref commented
Resolve conflicts.

2023-02-22 20:43 UTC, Faf4a commented
> Resolve conflicts.

Resolved.

2023-02-27 16:32 UTC, Leref requested changes
All needed before approving.

2023-02-27 16:32 UTC, Leref commented on src/functions/Awaited/awaitCmdReactions.md
> -    code: `
Keep the format same.

2023-02-27 16:32 UTC, Leref commented on src/functions/Awaited/reactionCollector.md
> -    name: "awaitReaction",
Keep format same.

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/broadcastEval.md
> -    name: 'broadcastEval',
Keep format same.

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/clear.md
> -    name: 'clear',
Keep format same.

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/kick.md
> +
Remove extra space.

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/killShard.md
> +
Remove extra space.

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/messagePublish.md
> +
Remove extra space

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/modifyApplicationCommand.md
> +
Remove extra space

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/modifyApplicationCommand.md
> +
Remove extra space

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/modifyChannelPerms.md
> +
Remove extra space

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/modifyChannelPerms.md
> +  // $guildID represents the @everyone role.
This should be placed somewhere else.

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/modifyEmoji.md
> +
Remove extra space

2023-02-27 16:32 UTC, Leref commented on src/functions/Calling/modifyEmoji.md
> +
Remove double space

2023-02-27 16:32 UTC, Leref commented on src/guides/6interaction.md
> -id: interactioncommands
Revert.

2023-02-27 16:32 UTC, Leref commented on src/guides/8others.md
> +In case this doesn't work, make sure you have a directory called "database", inside it a directory called "main" and a file called "main_scheme_1.sql" with the content of "{}".
Rephrase this

2023-02-27 17:19 UTC, Faf4a commented
Everything resolved.

2023-03-04 06:11 UTC, Faf4a commented
Finished `calling`, continuing on `misc`.

- Updated a few descriptions.
- Fixed some spacing.
- Other minor stuff.

2023-03-09 16:48 UTC, Faf4a commented
**Aoi.js Documentation Progress - Completed**

- Additions
> Completely finished all functions of all categories.
> Finished all guides.
> Double checks all functions, fixed things that were reported by users.
> Added `customfunction.md` and plenty of examples.

- Changes
> Updated the aoi.panel guide with latest pictures and updated formatting.
> Fixed minor things such as formatting breaking etc.
> Redid whole structures of most guides, (most of it wont be shown on the website).
> Improved guides greatly (again).
> >- Updated `4status.md` and added sharding explanation to it.
> >- Added visual explanation in form of images to most guides.
>      >- Added round corners to most images, perfection yk.
> >- Updated `aoi.music.md` to match other setups.
> >- Updated `introduction.md` to match other setups.

Everything should be fine as for now and updated to how it should be.

- Fafa

2023-03-14 12:15 UTC, Leref approved these changes

2023-03-14 12:15 UTC, merged