40 more functions added
AkaruiDevelopment/aoi.js-documentation pull request #2
Opened 2023-01-01 08:32 UTC by Faf4a

2023-01-01 10:06 UTC, Faf4a commented
_38 functions remaining_

2023-01-01 21:21 UTC, Faf4a commented
_adding examples, command handler, status etc tmrw as well as the remaining 15 functions_

2023-01-22 17:21 UTC, Leref requested changes

2023-01-22 17:21 UTC, Leref commented on src/functions/info/serverDefaultMessageNotifications .md
> +
There a blank space after `.md`

2023-01-22 17:26 UTC, Faf4a commented on src/functions/info/serverDefaultMessageNotifications .md
> +
fixed

2023-01-22 17:33 UTC, Leref approved these changes

2023-01-22 17:34 UTC, merged