Added panel's Documentation
AkaruiDevelopment/aoi.js-documentation pull request #6
Opened 2023-01-04 07:48 UTC by Bumblebee-3

2023-01-08 19:54 UTC, Leref requested changes
All of this must follow the syntax methods for AoiEngine to read.

title, description, and id are missing for each.

2023-01-14 09:24 UTC, Bumblebee-3 commented
Have updated it.

2023-01-28 13:52 UTC, Leref requested changes

2023-01-28 13:52 UTC, Leref commented on src/guides/@akarui/aoi.panel/advanced.md
> +title: akarui/aoi.panel
it doesn't need `akarui/` only the name.

2023-02-09 06:35 UTC, Bumblebee-3 commented on src/guides/@akarui/aoi.panel/advanced.md
> +title: akarui/aoi.panel
Have updated, Pls check

2023-02-22 04:47 UTC, Leref commented on src/guides/@akarui/aoi.panel/advanced.md
> +title: akarui/aoi.panel
The actual name syntax isn't updated.

2023-02-22 04:48 UTC, Leref requested changes
Must be changed before accepting.

2023-02-22 04:48 UTC, Leref commented on src/guides/akarui/aoi.panel/README.md
> +title: akarui/aoi.panel
it should be aoi.panel.

2023-02-22 04:48 UTC, Leref commented on src/guides/akarui/aoi.panel/advanced.md
> +title: akarui/aoi.panel
Remove akarui/aoi.panel and rename to according information title.

2023-02-22 04:48 UTC, Leref commented on src/guides/akarui/aoi.panel/funcs.md
> +title: akarui/aoi.panel
From previous comment.

2023-02-22 04:48 UTC, Leref commented on src/guides/akarui/aoi.panel/panel.md
> +title: akarui/aoi.panel
As well from previous comment.

2023-02-22 07:41 UTC, Bumblebee-3 commented
Have updated the docs, with Colours and code editor's info

2023-02-22 19:03 UTC, Leref approved these changes

2023-02-22 19:03 UTC, merged